package com.fops.infrastructure.persistence;

import com.fops.domain.enums.NotificationStatus;
import com.fops.domain.enums.OrderStatus;
import com.fops.domain.model.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.PageRequest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Custom queries and database constraints, against the real schema generated by Hibernate.
 */
@DataJpaTest
class RepositoryIT {

    private static final List<OrderStatus> OPEN = List.of(OrderStatus.PENDING, OrderStatus.PARTIALLY_FULFILLED);

    @Autowired
    private TestEntityManager em;
    @Autowired
    private OrderRepository orderRepository;
    @Autowired
    private ItemRepository itemRepository;
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private InventoryMovementRepository movementRepository;
    @Autowired
    private OrderNotificationRepository notificationRepository;
    @Autowired
    private JdbcTemplate jdbc;

    private User user;
    private Item item;

    @BeforeEach
    void setUp() {
        user = em.persist(new User("Ana", "ana@test.local"));
        item = em.persist(new Item("Laptop", "LAP-1"));
    }

    @Test
    void openOrdersComeBackOldestFirstAndExcludeCompletedOnes() {
        Order newer = persistOrder(5, LocalDateTime.now());
        Order older = persistOrder(5, LocalDateTime.now().minusHours(1));
        Order completed = persistOrder(1, LocalDateTime.now().minusHours(2));
        completed.allocate(1);
        em.flush();

        List<Order> open = orderRepository.findByItemAndStatusInOrderByCreatedAtAscIdAsc(item, OPEN);

        assertThat(open).containsExactly(older, newer);
    }

    @Test
    void ordersWithTheSameCreationTimeAreTieBrokenById() {
        LocalDateTime sameInstant = LocalDateTime.now();
        Order first = persistOrder(1, sameInstant);
        Order second = persistOrder(1, sameInstant);

        assertThat(orderRepository.findByItemAndStatusInOrderByCreatedAtAscIdAsc(item, OPEN)).containsExactly(first, second);
    }

    @Test
    void aggregatesStockAndOpenDemand() {
        Item other = em.persist(new Item("Mouse", "MOU-1"));
        item.increaseStock(7);
        persistOrder(4, LocalDateTime.now()).allocate(1);
        persistOrder(2, LocalDateTime.now());
        em.flush();

        assertThat(itemRepository.sumStockOnHand()).isEqualTo(7);
        assertThat(itemRepository.countByStockOnHand(0)).isEqualTo(1);
        assertThat(orderRepository.sumRemainingQuantityByStatusIn(OPEN)).isEqualTo(5);
        assertThat(orderRepository.countByStatus(OrderStatus.PARTIALLY_FULFILLED)).isEqualTo(1);
        assertThat(other.getStockOnHand()).isZero();
    }

    @Test
    void tracesMovementsByOrderAndBySourceMovement() {
        Order order = persistOrder(5, LocalDateTime.now());
        item.increaseStock(5);
        InventoryMovement in = em.persist(InventoryMovement.incoming(item, 5, "Delivery"));
        InventoryMovement out = em.persist(InventoryMovement.allocation(item, 5, order, in, true, "Allocated"));
        em.flush();

        assertThat(movementRepository.findByOrderIdChronological(order.getId())).containsExactly(out);
        assertThat(movementRepository.findBySourceMovementId(in.getId())).containsExactly(out);
        assertThat(movementRepository.findByItemIdChronological(item.getId())).containsExactly(in, out);
    }

    @Test
    void findsOnlyPendingNotificationsThatAreDue() {
        LocalDateTime now = LocalDateTime.now();
        Order due = completedOrder();
        Order notYet = completedOrder();
        Order sent = completedOrder();
        em.persist(new OrderNotification(due, now.minusMinutes(1)));
        em.persist(new OrderNotification(notYet, now.plusMinutes(5)));
        OrderNotification alreadySent = new OrderNotification(sent, now.minusMinutes(1));
        alreadySent.markSent(now);
        em.persist(alreadySent);
        em.flush();

        List<Long> dueIds = notificationRepository.findDueOrderIds(NotificationStatus.PENDING, now, PageRequest.of(0, 10));

        assertThat(dueIds).containsExactly(due.getId());
        assertThat(notificationRepository.countByStatus(NotificationStatus.PENDING)).isEqualTo(2);
    }

    @Test
    void allowsOnlyOneNotificationPerOrder() {
        Order order = completedOrder();
        em.persist(new OrderNotification(order, LocalDateTime.now()));

        assertThatThrownBy(() -> notificationRepository.saveAndFlush(new OrderNotification(order, LocalDateTime.now())))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void enforcesUniqueSkuAndEmailAtDatabaseLevel() {
        assertThatThrownBy(() -> itemRepository.saveAndFlush(new Item("Other", "LAP-1")))
                .isInstanceOf(DataIntegrityViolationException.class);
        em.clear();
        assertThatThrownBy(() -> userRepository.saveAndFlush(new User("Other", "ana@test.local")))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void databaseRejectsNegativeStockEvenIfTheDomainIsBypassed() {
        em.flush();

        assertThatThrownBy(() -> jdbc.update("update items set stock_on_hand = -1 where id = ?", item.getId()))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void userAndSkuLookupsIgnoreCase() {
        assertThat(userRepository.existsByEmailIgnoreCase("ANA@test.local")).isTrue();
        assertThat(itemRepository.existsBySkuIgnoreCase("lap-1")).isTrue();
    }

    private Order persistOrder(int quantity, LocalDateTime createdAt) {
        Order order = new Order(user, item, quantity);
        ReflectionTestUtils.setField(order, "createdAt", createdAt);
        return em.persist(order);
    }

    private Order completedOrder() {
        Order order = new Order(user, item, 1);
        order.allocate(1);
        return em.persist(order);
    }
}
